apiVersion: v1
kind: Service
metadata:
  name: poll-service
  namespace: default
  labels:
    app: poll
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
     name: http
  selector:
   app: poll