apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: kube-public
spec:
  selector:
    app: traefik
  ports:
  - port: 80
    targetPort: 30021
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 30042
    protocol: TCP
    name: admin
  type: NodePort
