apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: epitechcontent/t-dop-600-worker:k8s
        resources:
          limits:
            memory: "256mi"
            cpu: "100M"
        restartPolicy: Always
        envFrom:
          - configMapRef:
              name: postgres-config
<<<<<<< HEAD
          - secretRefPostgresql:
              name: postgres-secrets
          - configMapRefRedis:
=======
>>>>>>> 5603d29312ba8b49d4e5f00d34782f3dbe878d31
              name: redis-config
          - secretRef:
              name: postgres-secret
