apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      replicas: 2
      containers:
      - name: worker
        image: epitechcontent/t-dop-600-worker:k8s
        resources:
          limits:
            memory: "256m"
            cpu: "500M"
        restartPolicy: Always
        envFrom:
          - configMapRef:
              name: postgres-config
              name: redis-config
          - secretRef:
              name: postgres-secret
